# Builders defined by this package:
builders:
  extension_builder:
    import: "package:generic_enum_builder/generic_enum_builder.dart"
    builder_factories: ["extensionBuilder"]
    build_extensions: {".dart": ["extension_builder.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
