name: generic_enum_builder

description: Source code generator for package generic_enum.  Builds extensions
  containing value-mapping and json-serialization methods for annotated
  Dart enums.

version: 0.4.1

homepage: https://github.com/simphotonics/generic_enum/tree/main/generic_enum_builder

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^1.3.0
  build: ^2.0.0
  dart_style: ^2.0.0
  exception_templates: ^0.2.0
  generic_enum: ^0.4.0
  quote_buffer: ^0.2.2
  source_gen: ^1.0.0

dev_dependencies:
  build_runner: ^1.12.2
  crypto: ^3.0.0
  glob: ^2.0.1
  pedantic: ^1.11.0
  source_gen_test: ^1.0.0
  test: ^1.16.8

dependency_overrides: null

# generic_enum:
#   path: ../generic_enum
