name: generic_enum_builder
description: >
  Source code generator processing annotated generic_enum classes.
  Generates a value-instance map and a json-serialization  function.
version: 0.1.5
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_builder

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.4
  build: ^1.2.2
  dart_style: ^1.3.3
  generic_enum: ^0.1.6
  generic_enum_annotation: ^0.1.4
  meta: ^1.1.8
  source_gen: ^0.9.4+6


dev_dependencies:
  build_runner: ^1.7.4
  source_gen_test: ^0.1.0+6
  test: ^1.12.0