name: generic_enum_builder
description: >
  Source code generator processing annotated generic_enum classes.
  It builds a value-instance map and json-serialization functions.
version: 0.1.0
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_builder

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  analyzer: ^0.39.2+1
  build: ^1.1.6
  dart_style: ^1.3.3
  generic_enum: ^0.1.4
  generic_enum_annotation: ^0.1.1
  meta: ^1.1.6
  source_gen: ^0.9.4+6


dev_dependencies:
  built_collection: ^4.3.2
  build_runner: ^1.7.2
  source_gen_test: ^0.1.0+6
  test: ^1.11.1