name: generic_enum_builder

description:
  Source code generator processing annotated generic_enum classes.
  Generates a value-instance map and a json-serialization  function.

version: 0.2.4

homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_builder

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: ^0.39.10
  build: ^1.3.0
  dart_style: ^1.3.6
  generic_enum: ^0.2.5
  meta: ^1.1.8
  source_gen: ^0.9.5

dev_dependencies:
  build_runner: ^1.10.0
  source_gen_test: ^0.1.1
  test: ^1.14.7