name: generic_enum_builder

description:
  Source code generator for package generic_enum.  Builds extensions
  containing value-mapping and json-serialization methods for each annotated Dart enum.

version: 0.3.5

homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_builder

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: ^0.39.10
  build: ^1.3.0
  dart_style: ^1.3.6
  exception_templates: ^0.0.6
  generic_enum: ^0.3.5
  quote_buffer: ^0.1.5
  source_gen: ^0.9.6

dependency_overrides:
  # generic_enum:
  #   path: ../generic_enum

dev_dependencies:
  build_runner: ^1.10.0
  source_gen_test: ^0.1.1
  test: ^1.15.3
  pedantic: ^1.9.2