name: generic_enum
description:
  Provides a generic enumeration base class that
  can be extended to create simple enumeration classes with
  a generic value type. These classes can be used in
  switch statements, as annotations, or as constant parameters.

version: 0.0.4
homepage: https://github.com/simphotonics/generic_enum

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.11.0
