name: generic_enum
description:
  Enumeration classes with generic value type. Can be used in
  switch statements, as annotations, or as constant parameters
  in constructors and functions.

version: 0.0.6
homepage: https://github.com/simphotonics/generic_enum

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.11.0
