name: generic_enum
description:
  Extensions on Dart enums adding json-serialization and
  a mapping of enum instances to a constant with arbitrary value type.
  Works with generic_enum_builder.

version: 0.3.0
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  exception_templates: ^0.0.3

dev_dependencies:
  test: ^1.15.1
