name: generic_enum
description:
  Enumeration classes with generic value type. Can be used in
  switch statements, as annotations, or as constant parameters
  in constructors and functions.

version: 0.2.3
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  test: ^1.14.7
  build_runner: ^1.10.0
  json_serializable: ^3.3.0