name: generic_enum

description:
  Dart enumerations with extension-methods offering
  json-serialization and a mapping of each enum instance
  to a const value with arbitrary data-type.

version: 0.3.2
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  exception_templates: ^0.0.3
  meta: ^1.2.2

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.3
