name: generic_enum

description:
  Dart enumerations with extension-methods offering
  json-serialization and a mapping of each enum instance
  to a const value with arbitrary data-type.

version: 0.4.0-nnbd

homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:

dev_dependencies:
  exception_templates: ^0.0.6
  pedantic: ^1.9.2
  test: ^1.15.3
