name: generic_enum
description:
  Enumeration classes with generic value type. Can be used in
  switch statements, as annotations, or as constant parameters
  in constructors and functions.

version: 0.1.6
homepage: https://github.com/simphotonics/generic_enum

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  json_serializable: ^3.2.5