name: generic_enum
description:
  Enumeration classes with generic value type. Can be used in
  switch statements, as annotations, or as constant parameters
  in constructors and functions.

version: 0.2.7
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.15.0
