name: generic_enum
description:
  Enumeration classes with generic value type. Can be used in
  switch statements, as annotations, or as constant parameters
  in constructors and functions.

version: 0.1.2
homepage: https://github.com/simphotonics/generic_enum

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  built_collection: ^4.3.2
  json_annotation: ^3.0.1
  generic_enum_annotation: ^0.0.7

dev_dependencies:
  test: ^1.11.0
  build_runner: ^1.7.3
  json_serializable: ^3.2.5