name: generic_enum_annotation
description:
  Defines annotations processed by source code generating library generic_enum_generator.

version: 0.0.2
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_annotation

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
