name: generic_enum_annotation
description:
  Defines annotations processed by source code generating library `generic_enum_generator`.

version: 0.0.1
homepage: https://github.com/simphotonics/generic_enum
author: D Reschner <git@simphotonics.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
