name: generic_enum_annotation
description:
  Defines annotations processed by source code generating library generic_enum_builder.

version: 0.0.6
homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_annotation

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
