name: generic_enum_example

description: Demonstrates how to define and build extensions on Dart enums using
  the packages generic_enum and generic_enum_builder.

version: 0.4.3

homepage: https://github.com/simphotonics/generic_enum/tree/main/generic_enum_example

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  exception_templates: ^0.2.1
  generic_enum: ^0.4.3

dev_dependencies:
  build_runner: ^2.0.5
  generic_enum_builder: ^0.4.3
  pedantic: ^1.11.1

dependency_overrides:
  # generic_enum:
  #   path: ../generic_enum
  # generic_enum_builder:
  #   path: ../generic_enum_builder
