name: generic_enum_example

description:
  Demonstrates how to define and build extensions on Dart enums
  using the packages generic_enum and generic_enum_builder.

version: 0.4.0-nnbd

homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_example

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  exception_templates: ^0.0.3
  generic_enum: ^0.3.4

dev_dependencies:
  build_runner: ^1.10.0
  #generic_enum_builder: ^0.3.5
  generic_enum_builder:
    git:
      url: https://github.com/simphotonics/generic_enum.git
      ref: nnbd
      path: generic_enum_builder

dependency_overrides:
  generic_enum:
    path: ../generic_enum
  # generic_enum_builder:
  #   path: ../generic_enum_builder
