name: generic_enum_example

description:
  Demonstrates how to define and build extensions on Dart enums
  using the packages generic_enum and generic_enum_builder.

version: 0.3.0

homepage: https://github.com/simphotonics/generic_enum/tree/master/generic_enum_example

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  exception_templates: ^0.0.3
  generic_enum: ^0.3.1

dev_dependencies:
  build_runner: ^1.10.0
  generic_enum_builder: ^0.3.0
