name: generic_enum_example

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  generic_enum_annotation: ^0.0.4
  generic_enum: ^0.0.6
  built_collection: ^4.3.2

dev_dependencies:
  build_runner: ^1.0.0
  source_gen: ^0.9.4+7
  generic_enum_generator:
    path: ../generic_enum_generator



# Used by tests. Not required to use `json_serializable`.
#   build_verify: ^1.0.0
#   path: ^1.5.1
#   test: ^1.6.0

# dependency_overrides:
#   json_serializable:
#     path: ../json_serializable